Repository AY2425S1-CS2103T-T16-1/tp, pull requests merged in 2024-10, with the labels that each got.

#15 Add Jalen's image
  docs/images/jalenleeruixian.png
Labels: type.Task

#13 Add hejun image
  docs/images/testing1234567891011121314.png
Labels: type.Task

#26 Update hejun AboutUs
  docs/AboutUs.md
Labels: type.Task

#22 Add Wei Zhi's AboutUs
  docs/AboutUs.md
Labels: type.Task

#33 Update DG use cases
  docs/DeveloperGuide.md
Labels: type.Task

#46 Update DeveloperGuide
  docs/DeveloperGuide.md
Labels: type.Task

#49 Add import function
  src/main/java/seedu/address/ui/ImportWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/ImportWindow.css
  src/main/resources/view/ImportWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Story, type.Task, priority.High

#50 Add Authentication
  docs/DeveloperGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/authentication/Authentication.java
  src/main/java/seedu/address/ui/LoginWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/Ui.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/ImportWindow.css
  src/main/resources/view/LoginWindow.fxml
Labels: type.Story, priority.High

#53 V1.2
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/StatusBarFooter.fxml
Labels: priority.High

#61 Add CheckStyle
  src/main/java/seedu/address/ui/ImportWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/ImportWindow.fxml
Labels: severity.VeryLow

#62 Change Checkstyle
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High

#70 Add count command
  src/main/java/seedu/address/logic/commands/CountCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CountCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.High

#72 Branch update auth
  src/main/java/seedu/address/authentication/Authentication.java
  src/main/java/seedu/address/authentication/Credentials.java
  src/main/java/seedu/address/authentication/credentials.txt
  src/main/java/seedu/address/ui/LoginWindow.java
  src/main/resources/view/LoginWindow.fxml
  src/test/java/seedu/address/authentication/CredentialsTest.java
  src/test/java/seedu/address/authentication/test.txt
Labels: priority.Medium, severity.Medium

#77 Improve personal detail window
  src/main/java/seedu/address/authentication/credentials.txt
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonDetailsWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/PersonDetailsWindow.fxml
Labels: priority.Medium

#88 Update Authentication UML
  docs/diagrams/AuthenticationClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/style.puml
Labels: type.Task, priority.High

#81 Improve personal details window interaction
  src/main/java/seedu/address/ui/PersonDetailsWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/PersonDetailsWindow.fxml
Labels: priority.Medium

#92 Add Assertion
  src/main/java/seedu/address/logic/commands/CountCommand.java
Labels: type.Task

#91 Add Assertions
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/address/ui/PersonDetailsWindow.java
Labels: type.Task

#85 Branch add favourite field
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FavoriteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#96 Branch add puml
  docs/diagrams/ModelClassDiagram.puml
Labels: priority.High

#90 Add Assertions
  build.gradle
  src/main/java/seedu/address/authentication/Authentication.java
  src/main/java/seedu/address/authentication/Credentials.java
Labels: type.Task

#107 Add Leave Field
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FavoriteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Leave.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/config/credentials.txt
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#108 Update person details window
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/ui/PersonDetailsWindow.java
  src/main/resources/view/PersonDetailsWindow.fxml
Labels: priority.High

#136 Update help
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: alpha-bug
