Repository AY2425S1-CS2103T-T16-1/tp, pull requests merged in 2024-11, with the labels that each got.

#140 Update UG of person detail window
  docs/UserGuide.md
  docs/images/persondetailswindow.png
Labels: priority.High

#141 Add bug fix
  src/main/java/seedu/address/logic/parser/CountCommandParser.java
Labels: priority.Medium, alpha-bug

#145 Branch user guide
  docs/UserGuide.md
  docs/images/authentication.png
  src/main/java/seedu/address/authentication/Hashing.java
  src/main/java/seedu/address/logic/Messages.java
Labels: alpha-bug

#269 Add More Screenshots to UG
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/favorite.png
  docs/images/helpMessage.png
Labels: priority.Low

#271 Update UG and fix some bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/CountCommandParser.java
Labels: priority.Medium

#291 Add Screenshots for Each Command in UG
  docs/UserGuide.md
  docs/images/add.png
  docs/images/clear.png
  docs/images/count.png
  docs/images/delete.png
  docs/images/edit.png
  docs/images/favorite.png
  docs/images/find.png
  docs/images/list.png
  docs/images/sort.png
  src/main/java/seedu/address/logic/commands/ClearCommand.java
Labels: priority.High
